import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const SUPABASE_URL = 'https://enzqritietjhrdezdkxj.supabase.co';
const SUPABASE_KEY = 'sb_publishable_tzzD7ia5MXerBKnREOzAvA_7duHc6Lr';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
  auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true },
});

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const state = { session:null, profile:null, profiles:[], channels:['general'], activeChannel:'general', currentPage:'home', deferredInstall:null, subscriptions:[] };

const fmtDate = (d) => d ? new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${d}T12:00:00`)) : '—';
const fmtTime = (t) => t ? String(t).slice(0,5) : '—';
const fmtTs = (ts) => ts ? new Intl.DateTimeFormat(undefined,{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(ts)) : '';
const safe = (v='') => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials = (name='?') => name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join('') || '?';
function toast(message,type='info'){ const e=document.createElement('div'); e.className=`toast ${type==='error'?'error':''}`; e.textContent=message; $('#toastHost').append(e); setTimeout(()=>e.remove(),3800); }
function empty(text){ return `<div class="empty">${safe(text)}</div>`; }
function roleRank(role){ return ({owner:3,admin:2,driver:1}[String(role||'').toLowerCase()]||0); }
function effectiveRole(p){ return roleRank(p?.secondary_role)>roleRank(p?.role)?p.secondary_role:p?.role; }
function hasTag(p,tag){ return Array.isArray(p?.role_tags)&&p.role_tags.some(x=>String(x).toLowerCase()===tag.toLowerCase()); }

window.addEventListener('error', e => toast(`Error: ${e.message}`,'error'));
window.addEventListener('unhandledrejection', e => toast(`Error: ${e.reason?.message || e.reason || 'Unexpected error'}`,'error'));
window.addEventListener('online', updateOnlineState); window.addEventListener('offline', updateOnlineState);
function updateOnlineState(){ $('#offlineBanner').classList.toggle('hidden',navigator.onLine); $('#connectionLabel').textContent=navigator.onLine?'Connected':'Offline'; }

$('#togglePassword').addEventListener('click',()=>{ const i=$('#password'); i.type=i.type==='password'?'text':'password'; });
$('#loginForm').addEventListener('submit', async e=>{ e.preventDefault(); $('#loginError').classList.add('hidden'); const {error}=await supabase.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value}); if(error){ $('#loginError').textContent=error.message; $('#loginError').classList.remove('hidden'); } });

supabase.auth.onAuthStateChange((_event,session)=>{ state.session=session; if(session) enterApp(); else showLogin(); });
const {data:{session}} = await supabase.auth.getSession(); state.session=session; session ? await enterApp() : showLogin();

function showLogin(){ cleanupSubscriptions(); $('#loginView').classList.remove('hidden'); $('#appView').classList.add('hidden'); }
async function enterApp(){ $('#loginView').classList.add('hidden'); $('#appView').classList.remove('hidden'); await loadProfile(); await Promise.allSettled([loadProfiles(),loadHome(),loadEvents(),loadChannels(),loadMessages(),loadDMRecipients(),loadPolls()]); startRealtime(); }

async function loadProfile(){ const uid=state.session.user.id; const {data,error}=await supabase.from('profiles').select('*').eq('id',uid).maybeSingle(); if(error) toast(error.message,'error'); state.profile=data||{id:uid,full_name:state.session.user.email,role:'driver'}; $('#avatarInitials').textContent=initials(state.profile.full_name||state.profile.nickname||'?'); }
async function loadProfiles(){ const {data,error}=await supabase.from('profiles').select('*').eq('active',true).order('full_name'); if(error){toast(error.message,'error');return;} state.profiles=data||[]; fillDMRecipients(); }

function nav(page){ state.currentPage=page; $$('.page').forEach(p=>p.classList.add('hidden')); $(`.page[data-page="${page}"]`)?.classList.remove('hidden'); $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===page)); window.scrollTo({top:0,behavior:'instant'}); if(page==='home')loadHome(); if(page==='events')loadEvents(); if(page==='chat')loadMessages(); }
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
$('#profileButton').addEventListener('click',()=>showSubpage('settings'));
$('#backMore').addEventListener('click',()=>nav('more'));
$$('[data-subpage]').forEach(b=>b.addEventListener('click',()=>showSubpage(b.dataset.subpage)));

async function loadHome(){ renderHomeProfile(); const [ev,act,not]=await Promise.all([
  supabase.from('events').select('*').gte('event_end_date',new Date().toISOString().slice(0,10)).order('event_date').limit(3),
  supabase.from('activity_log').select('*').order('created_at',{ascending:false}).limit(5),
  supabase.from('notifications').select('*').eq('user_id',state.session.user.id).order('created_at',{ascending:false}).limit(5)
]);
  $('#homeEvents').innerHTML=ev.error?empty('Events unavailable'):renderEvents(ev.data||[],true);
  $('#homeActivity').innerHTML=act.error?empty('No activity available'):(act.data?.length?act.data.map(a=>`<div class="list-card"><div class="card-icon">↻</div><div><strong>${safe(a.action||'Activity')}</strong><p>${safe(a.details||a.entity_type||'')}</p><small>${fmtTs(a.created_at)}</small></div></div>`).join(''):empty('No recent activity'));
  $('#homeNotifications').innerHTML=not.error?empty('Notifications unavailable'):(not.data?.length?not.data.map(n=>`<div class="list-card"><div class="card-icon">${n.is_read?'○':'●'}</div><div><strong>${safe(n.title||'Notification')}</strong><p>${safe(n.message||'')}</p><small>${fmtTs(n.created_at)}</small></div></div>`).join(''):empty('No notifications'));
}
function renderHomeProfile(){ const p=state.profile||{}; $('#homeProfile').innerHTML=`<p class="eyebrow">Signed in</p><h3>${safe(p.full_name||p.nickname||'Team member')}</h3><p>${safe(p.nickname||'')} ${p.race_number?`#${safe(p.race_number)}`:''}</p><div class="profile-tags"><span class="tag white">${safe(effectiveRole(p)||'Driver')}</span>${hasTag(p,'LMU Driver')?'<span class="tag">LMU Driver</span>':''}${hasTag(p,'iRacing Driver')?'<span class="tag">iRacing Driver</span>':''}</div>`; }

async function loadEvents(){ $('#eventsList').innerHTML='<div class="empty">Loading events…</div>'; const {data,error}=await supabase.from('events').select('*').order('event_date',{ascending:false}).limit(50); if(error){$('#eventsList').innerHTML=empty(error.message);return;} $('#eventsList').innerHTML=renderEvents(data||[],false); }
function renderEvents(events,compact=false){ if(!events.length)return empty('No events yet'); return events.map(e=>`<button class="event-card" data-event-id="${e.id}"><div class="event-top"><div><strong>${safe(e.name)}</strong><p>${safe(e.championship||e.simulation||'')}</p></div><span class="status-pill">${safe(e.status||'scheduled')}</span></div><div class="event-meta"><div class="meta-box"><small>Date</small><span>${fmtDate(e.event_date)} ${fmtTime(e.start_time)}</span></div><div class="meta-box"><small>Track</small><span>${safe(e.track||'—')}</span></div></div>${compact?'':`<p>${safe(e.notes||'')}</p>`}</button>`).join(''); }
document.addEventListener('click',e=>{ const btn=e.target.closest('[data-event-id]'); if(btn) showEventDetail(btn.dataset.eventId); });
async function showEventDetail(id){ nav('subpage'); $('#subpageContent').innerHTML='<div class="empty">Loading event…</div>'; const [ev,en,at]=await Promise.all([
 supabase.from('events').select('*').eq('id',id).single(),
 supabase.from('event_entries').select('*').eq('event_id',id).order('created_at'),
 supabase.from('event_attendance').select('*').eq('event_id',id)
]); if(ev.error){$('#subpageContent').innerHTML=empty(ev.error.message);return;} const entries=en.data||[]; let driverMap={}; if(entries.length){ const {data:eds}=await supabase.from('event_entry_drivers').select('*').in('entry_id',entries.map(x=>x.id)); for(const d of eds||[])(driverMap[d.entry_id]??=[]).push(d.driver_id); }
 const attendance=at.data||[]; $('#subpageContent').innerHTML=`<div class="page-heading"><p class="eyebrow">${safe(ev.data.simulation||'Event')}</p><h2>${safe(ev.data.name)}</h2></div><div class="hero-card"><p>${safe(ev.data.championship||'')}</p><h3>${safe(ev.data.track||'—')}</h3><p>${fmtDate(ev.data.event_date)} · ${fmtTime(ev.data.start_time)}</p></div><div class="section-title"><h3>Line-ups</h3></div><div class="card-list">${entries.length?entries.map(x=>`<div class="list-card"><div class="card-icon">#${safe(x.car_number||'')}</div><div><strong>${safe(x.entry_name||'Line-up')}</strong><p>${safe(x.vehicle||'')} · ${(driverMap[x.id]||[]).map(uid=>safe(state.profiles.find(p=>p.id===uid)?.full_name||'Driver')).join(', ')||'No drivers'}</p></div></div>`).join(''):empty('No line-ups')}</div><div class="section-title"><h3>Attendance</h3></div><div class="card-list">${attendance.length?attendance.map(a=>`<div class="list-card"><div class="card-icon">•</div><div><strong>${safe(state.profiles.find(p=>p.id===a.driver_id)?.full_name||'Driver')}</strong><p>${safe(a.status)}</p></div></div>`).join(''):empty('No attendance responses')}</div>`; }

async function loadChannels(){ const {data}=await supabase.from('messages').select('channel').limit(500); const set=new Set((data||[]).map(x=>x.channel).filter(Boolean)); ['general','announcements','race-chat'].forEach(x=>set.add(x)); state.channels=[...set].sort(); $('#channelSelect').innerHTML=state.channels.map(c=>`<option ${c===state.activeChannel?'selected':''}>${safe(c)}</option>`).join(''); }
$('#channelSelect').addEventListener('change',e=>{state.activeChannel=e.target.value;loadMessages();loadPolls();});
async function loadMessages(){ const {data,error}=await supabase.from('messages').select('*').eq('channel',state.activeChannel).order('created_at',{ascending:true}).limit(100); if(error){$('#messagesList').innerHTML=empty(error.message);return;} renderMessages(data||[], '#messagesList'); }
function renderMessages(items,selector){ const box=$(selector); if(!items.length){box.innerHTML=empty('No messages yet');return;} box.innerHTML=items.map(m=>{const p=state.profiles.find(x=>x.id===m.sender_id);const mine=m.sender_id===state.session.user.id;return `<div class="message ${mine?'mine':''}"><div class="message-head">${safe(p?.nickname||p?.full_name||'Driver')}</div><div class="message-body">${safe(m.message||'')}</div><small>${fmtTs(m.created_at)}</small></div>`}).join(''); box.scrollTop=box.scrollHeight; }
$('#messageForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#messageInput'),msg=input.value.trim();if(!msg)return;const {error}=await supabase.from('messages').insert({channel:state.activeChannel,sender_id:state.session.user.id,message:msg});if(error)return toast(error.message,'error');input.value='';loadMessages();});
$('#refreshChat').addEventListener('click',()=>{loadChannels();loadMessages();loadPolls();});

function fillDMRecipients(){ $('#dmRecipient').innerHTML='<option value="">Choose member…</option>'+state.profiles.filter(p=>p.id!==state.session?.user?.id).map(p=>`<option value="${p.id}">${safe(p.full_name||p.nickname||'Driver')}</option>`).join(''); }
$('#dmRecipient').addEventListener('change',loadDMs);
async function loadDMs(){ const other=$('#dmRecipient').value;if(!other){$('#dmList').innerHTML=empty('Choose a member');return;}const uid=state.session.user.id;const {data,error}=await supabase.from('direct_messages').select('*').or(`and(sender_id.eq.${uid},recipient_id.eq.${other}),and(sender_id.eq.${other},recipient_id.eq.${uid})`).order('created_at',{ascending:true}).limit(100);if(error){$('#dmList').innerHTML=empty(error.message);return;}renderMessages(data||[],'#dmList'); }
$('#dmForm').addEventListener('submit',async e=>{e.preventDefault();const other=$('#dmRecipient').value,msg=$('#dmInput').value.trim();if(!other)return toast('Choose a member first','error');if(!msg)return;const {error}=await supabase.from('direct_messages').insert({sender_id:state.session.user.id,recipient_id:other,message:msg});if(error)return toast(error.message,'error');$('#dmInput').value='';loadDMs();});

$$('[data-chat-tab]').forEach(b=>b.addEventListener('click',()=>{ $$('[data-chat-tab]').forEach(x=>x.classList.toggle('active',x===b)); $('#chatChannelsPane').classList.toggle('hidden',b.dataset.chatTab!=='channels'); $('#chatDmsPane').classList.toggle('hidden',b.dataset.chatTab!=='dms'); $('#chatPollsPane').classList.toggle('hidden',b.dataset.chatTab!=='polls'); if(b.dataset.chatTab==='dms')loadDMs(); if(b.dataset.chatTab==='polls')loadPolls(); }));

$('#messageInput').addEventListener('input',e=>renderMentionSuggestions(e.target));
function renderMentionSuggestions(input){ const m=input.value.match(/(?:^|\s)@([\w-]*)$/); const box=$('#mentionSuggestions'); if(!m){box.classList.add('hidden');return;} const q=m[1].toLowerCase(); const staticTags=['drivers','admins','lmu','iracing']; const users=state.profiles.map(p=>({key:(p.nickname||p.full_name||'').replace(/\s+/g,''),label:p.nickname||p.full_name})); const options=[...staticTags.map(x=>({key:x,label:`@${x}`})),...users].filter(x=>x.key.toLowerCase().includes(q)).slice(0,8); if(!options.length){box.classList.add('hidden');return;} box.innerHTML=options.map(o=>`<button class="mention-item" data-mention="${safe(o.key)}">${safe(o.label)}</button>`).join(''); box.classList.remove('hidden'); }
$('#mentionSuggestions').addEventListener('click',e=>{const b=e.target.closest('[data-mention]');if(!b)return;const i=$('#messageInput');i.value=i.value.replace(/@([\w-]*)$/,`@${b.dataset.mention} `);$('#mentionSuggestions').classList.add('hidden');i.focus();});

async function loadPolls(){ const {data,error}=await supabase.from('polls').select('*,poll_options(*)').eq('channel',state.activeChannel).order('created_at',{ascending:false}).limit(20); if(error){$('#pollsList').innerHTML=empty('Polls unavailable');return;} const polls=data||[]; $('#pollsList').innerHTML=polls.length?polls.map(p=>`<div class="rule-card"><div><strong>${safe(p.question)}</strong><p>${p.multiple_choice?'Multiple answers':'One answer'}${p.closes_at?` · closes ${fmtTs(p.closes_at)}`:''}</p><div class="profile-tags">${(p.poll_options||[]).map(o=>`<span class="tag">${safe(o.option_text)}</span>`).join('')}</div></div></div>`).join(''):empty('No polls in this channel'); }

async function showSubpage(kind){ nav('subpage'); const c=$('#subpageContent'); c.innerHTML='<div class="empty">Loading…</div>'; if(kind==='team') return renderTeam(c); if(kind==='training') return renderTraining(c); if(kind==='results') return renderResults(c); if(kind==='rules') return renderRules(c); if(kind==='files') return renderFiles(c); if(kind==='settings') return renderSettings(c); }
async function renderTeam(c){ await loadProfiles(); c.innerHTML=`<div class="page-heading"><p class="eyebrow">Members</p><h2>Team</h2></div><div class="card-list">${state.profiles.map(p=>`<div class="list-card"><div class="profile-avatar">${p.avatar_url?`<img src="${safe(p.avatar_url)}" alt="" class="profile-avatar">`:initials(p.full_name||p.nickname)}</div><div><strong>${safe(p.full_name||p.nickname||'Driver')} ${p.race_number?`#${safe(p.race_number)}`:''}</strong><p>${safe(effectiveRole(p)||'Driver')} · ${safe(p.country||'')}</p><div class="profile-tags">${hasTag(p,'LMU Driver')?'<span class="tag">LMU Driver</span>':''}${hasTag(p,'iRacing Driver')?'<span class="tag">iRacing Driver</span>':''}</div></div></div>`).join('')}</div>`; }
async function renderTraining(c){ const {data,error}=await supabase.from('training_sessions').select('*').order('session_date',{ascending:false}).limit(50); c.innerHTML=`<div class="page-heading"><p class="eyebrow">Practice</p><h2>Training</h2></div><div class="card-list">${error?empty(error.message):(data?.length?data.map(t=>`<div class="event-card"><div class="event-top"><div><strong>${safe(t.title)}</strong><p>${safe(t.simulation||'')} · ${safe(t.track||'')}</p></div><span class="status-pill">${safe(t.status||'planned')}</span></div><div class="event-meta"><div class="meta-box"><small>Date</small><span>${fmtDate(t.session_date)} ${fmtTime(t.start_time)}</span></div><div class="meta-box"><small>Duration</small><span>${t.duration_minutes||'—'} min</span></div></div></div>`).join(''):empty('No training sessions'))}</div>`; }
async function renderResults(c){ const {data,error}=await supabase.from('results').select('*').order('created_at',{ascending:false}).limit(50); c.innerHTML=`<div class="page-heading"><p class="eyebrow">Performance</p><h2>Results</h2></div><div class="card-list">${error?empty(error.message):(data?.length?data.map(r=>`<div class="result-card"><div><strong>${safe(r.simulation||'Result')} · ${safe(r.track||'')}</strong><p>Start P${r.start_position??'—'} → Finish P${r.finish_position??'—'} · ${safe(r.vehicle||'')}</p></div></div>`).join(''):empty('No results'))}</div>`; }
async function renderRules(c){ const {data,error}=await supabase.from('team_rules').select('*').eq('active',true).order('sort_order'); c.innerHTML=`<div class="page-heading"><p class="eyebrow">Governance</p><h2>Rules</h2></div><div class="card-list">${error?empty(error.message):(data?.length?data.map(r=>`<div class="rule-card"><div><span class="tag">${safe(r.category||'General')}</span><strong style="display:block;margin-top:10px">${safe(r.title)}</strong><p>${safe(r.body)}</p></div></div>`).join(''):empty('No active rules'))}</div>`; }
async function renderFiles(c){ const {data,error}=await supabase.from('team_files').select('*').order('created_at',{ascending:false}).limit(50); c.innerHTML=`<div class="page-heading"><p class="eyebrow">Resources</p><h2>Files</h2></div><div class="card-list">${error?empty(error.message):(data?.length?data.map(f=>`<a class="file-card" href="${safe(f.external_url||f.storage_url||'#')}" target="_blank" rel="noopener"><div class="card-icon">↗</div><div><strong>${safe(f.name)}</strong><p>${safe(f.category||'')} · ${safe(f.description||'')}</p></div></a>`).join(''):empty('No team files'))}</div>`; }
function renderSettings(c){ const p=state.profile||{}; c.innerHTML=`<div class="page-heading"><p class="eyebrow">Account</p><h2>Settings</h2></div><div class="hero-card"><div class="profile-row"><div class="profile-avatar">${initials(p.full_name||p.nickname)}</div><div><strong>${safe(p.full_name||p.nickname||state.session.user.email)}</strong><p>${safe(state.session.user.email)}</p></div></div><div class="divider"></div><div class="settings-row"><div><strong>Role</strong><p>${safe(effectiveRole(p)||'Driver')}</p></div></div><div class="settings-row"><div><strong>PWA</strong><p>Add SABIL GR Hub to your Home Screen</p></div><button id="settingsInstall">Install</button></div><div class="settings-row"><div><strong>Session</strong><p>Same Supabase account as Windows</p></div><button id="logoutBtn" class="danger-btn">Log out</button></div></div>`; $('#logoutBtn').onclick=()=>supabase.auth.signOut(); $('#settingsInstall').onclick=installPwa; }

function cleanupSubscriptions(){ for(const ch of state.subscriptions){try{supabase.removeChannel(ch)}catch{}} state.subscriptions=[]; }
function startRealtime(){ cleanupSubscriptions(); const msg=supabase.channel('mobile-messages').on('postgres_changes',{event:'*',schema:'public',table:'messages'},payload=>{ if(state.currentPage==='chat' && (payload.new?.channel===state.activeChannel||payload.old?.channel===state.activeChannel))loadMessages(); }).subscribe(); const dm=supabase.channel('mobile-dms').on('postgres_changes',{event:'*',schema:'public',table:'direct_messages'},()=>{if(state.currentPage==='chat'&&!$('#chatDmsPane').classList.contains('hidden'))loadDMs();}).subscribe(); const ev=supabase.channel('mobile-events').on('postgres_changes',{event:'*',schema:'public',table:'events'},()=>{if(state.currentPage==='events')loadEvents();if(state.currentPage==='home')loadHome();}).subscribe(); state.subscriptions=[msg,dm,ev]; }

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#installButton').classList.remove('hidden');});
$('#installButton').addEventListener('click',installPwa);
async function installPwa(){ if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$('#installButton').classList.add('hidden');}else{toast('On iPhone: Share → Add to Home Screen');} }

if('serviceWorker' in navigator){ window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{})); }
updateOnlineState();
